### ISSUE TITLE
APK install is not working properly

### ISSUE THREAD

**Issue by 0EskiDost0** [kefir500/apk-editor-studio#10]
When installing via "APK install", the original is installed, not the modification

**Comment by Ibuprophen** [comment]
Just to clarify something I'm not sure your aware of... 

Based upon the following link here... 

https://github.com/kefir500/apk-editor-studio

... You'll notice that, under the `Setting Up` list, it states the requirement `adb - to install APK and manage Android devices`. This means that the ADB Drivers are not inclusive with this software. 

There's a ton of places, locations, websites, etc.... that has a ton of different versions, variations, etc... of the required ADB. 

I don't typically use this as I've only (at the moment) got Samsung devices and those drivers already has its own version of the ADB. 

I do know of the following link that does have the information and downloads that are reputable. 

https://www.xda-developers.com/what-is-adb/

It provides a little guide as well. 

This is the best guidance that I can help you with and I do wish you the best of luck! :-) 


~Ibuprophen

**Comment by kefir500** [comment]
@0EskiDost0
- Is the modified APK saved before installing?
- Does APK Editor Studio report any errors in the log panel *(top left panel by default)*?
- Also, try increasing the "Version Code" parameter *(top right panel by default)*.

@Ibuprophen

Actually, `adb` is deployed with the APK Editor Studio. "Setting Up" is a part of the "Compilation" section which refers to a manual compilation from sources.

**Comment by 0EskiDost0** [comment]
@kefir500
* No
* No errors
* Did not help

**Comment by kefir500** [comment]
Regarding you first answer: you should **save your APK** if you made any changes to it, otherwise the workspace refers to the original APK file which is obviously being installed on your device. In fact, APK Editor Studio should automatically suggest to save APK before installing it (except for several cases which will be fixed in future releases).

**Comment by 0EskiDost0** [comment]
@kefir500

Well, next time I’ll save before installation.  But still it’s not very convenient.

**Comment by Ibuprophen** [comment]
@kefir500, my last comment was regarding the ADB itself connecting to the device and not regarding the software's ability to utilize the ADB. 

@0EskiDost0, is this making sense to you or am I completely out of the park?


~Ibuprophen

**Comment by kefir500** [comment]
@0EskiDost0 Please, let me know if pre-saving the APK works fine. Regarding the convenience: as the ADB (official Android tool used by APK Editor Studio to install apps) only allows the installation of solid, packed APK files, the APK should be saved to a file anyway -- in order to be packed and signed.

@Ibuprophen Probably I'm missing your point, but APK Editor Studio contains ADB and ADB-related files, so the APK installation should work out of the box with most devices. In any case, @0EskiDost0 commented that APK Editor Studio reported no errors on APK installation, so it seems that ADB is working fine in this case.

**Comment by Ibuprophen** [comment]
Yeah... It looks like I'm off the mark on this my friend... LOL! 

I'm thinking about a different aspect of the ADB. My Apologies. 


~Ibuprophen

**Comment by 0EskiDost0** [comment]
@kefir500 pre-saving the APK works fine.

**Comment by kefir500** [comment]
@0EskiDost0
I've been going through the old issues and came across the minor bug which caused the behavior you described. I made the fix in 0e3690f, the upcoming v1.5.0 will include it.
