### ISSUE TITLE
brut.common.brutexception

### ISSUE THREAD

**Issue by jayce211** [kefir500/apk-editor-studio#11]
So I tried this out today, took an APK from the google playstore that I have been trying to modify with APKTOOL as well, but it seems this editor has the same issue. Here is the two errors I am seeing.

C:\Users\admin\AppData\Local\Temp\apk-editor-studio\apk\{98c956b2-d76f-4d33-9c59-0db18bce18a4}\res\values\public.xml:152: error: Public symbol ^attr-private/actionBarItemBackground declared here is not defined.

brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1):

**Comment by kefir500** [comment]
APK Editor Studio provides GUI over the **Apktool** which is used under the hood, so that is why the errors are identical. Since you have already created the corresponding [issue](https://github.com/iBotPeaches/Apktool/issues/2164) in the Apktool repo, I'm closing this one, as the repacking process depends heavily on Apktool.
