### ISSUE TITLE
java: Process failed to start: The system cannot find the file specified.

### ISSUE THREAD

**Issue by Adityakantkushwaha** [kefir500/apk-editor-studio#156]
![image](https://github.com/user-attachments/assets/ff27b8a0-2bb1-4cdd-a63b-aa93ec9b24bf)

**Comment by Ibuprophen** [comment]
Do you have the Required Java Software Installed? 

~Ibuprophen

**Comment by cgl-bsh** [comment]
@Ibuprophen : why not bundle java also ? some (most?) people don't have a(n up2date) java vm installed ? 
see also #156

**Comment by Ibuprophen** [comment]
@cgl-bsh, This question can only be answered by @kefir500 since he's the developer. 

As with many software packages that requires Java, it's much easier to provide a list of requirements rather than creating more work with implementing something like Java. 

I don't believe that @kefir500 has the time and resources to upkeep a second implementation like this. 

I hope I had explained this okay via text... 👍 

~Ibuprophen

**Comment by cgl-bsh** [comment]
You explained well, however, the idea of providing "appimages" (or the likes) is for the user to be able to run the software "anywhere" -  without any dependencies on his system...

**Comment by kefir500** [comment]
@Adityakantkushwaha

[Ibuprophen](https://github.com/Ibuprophen) is right, you need to install [Java](https://java.com/en/download) in order to run the underlying third-party Apktool.
This requirement is stated on the Download page of the APK Editor Studio website.

@cgl-bsh

No doubt, bundling Java with APK Editor Studio would be handy.
However, this would also bloat the size of the APK Editor Studio packages.
For example, some features require JDK (not just JRE) which can be around 200 MB.
So the APK Editor Studio would become ×5 larger in size, which is not the greatest result in my opinion.

Moreover, since APK Editor Studio is supported across 3 different platforms and is distributed via CI/CD, this would be a pain for me (as a single developer of this project) to support this kind of deployment.

However, I have plans on adding the automatic Java downloader which would download OpenJDK if it is not present on the target system. This feature is already partially implemented on my local machine, so I hope it will see the light of the day in the future releases.
