### ISSUE TITLE
Allow multiple instances

### ISSUE THREAD

**Issue by muznyo** [kefir500/apk-editor-studio#19]
Please add feature to open the apk editor studio in multiple instances (windows), because it's better if you switch between projects.

**Comment by kefir500** [comment]
Hi,
Currently you can switch between projects using the combo box in the Projects panel.
Could you please elaborate why do you prefer multiple instances instead?

**Comment by muznyo** [comment]
The combobox always resets the folders view to their original state, so after every switch i have to click through the folders to get the folder i want to work with

**Comment by kefir500** [comment]
I decided to keep a single *application* instance and added an option to have multiple *window* instances. The main reason for this decision is to have an ability to share the list of currently open projects between instances.

The test support was implemented in this commit: 238804e
You can turn this option on/off using the *Settings -> Options -> Single-window mode* checkbox.

You can [download](https://github.com/kefir500/apk-editor-studio/releases/tag/development) the CI snapshot build for testing (with an exception for the Windows MSI installer, as this particular build is currently broken and outdated). Note that these builds may contain bugs, since this feature required some significant refactoring spreaded across multiple commits.
