### ISSUE TITLE
Project improvements proposal

### ISSUE THREAD

**Issue by bovirus** [kefir500/apk-editor-studio#27]
@kefir500 

Switch default to 1.5.0 (current beta).
master (1.4.0) it's a close project because you are working on 1.5.0.

Update language files for 1.5.0 in **_src/translations_**

Modifiy **_/src/translations/translation.pri_** to add missing languages (not included in github repository but more than 50% translted in transliflex repository - ex Italian).

Modify source code to have a multi-language installer (with same language of GUI languages).

**Comment by kefir500** [comment]
Hi @bovirus,

### Project Translation

Thanks a lot for your contribution on the Italian translation, I will add it to the `1.5.0` branch as soon as possible.

For the future readers I'll describe the translation workflow:
- To improve the crowdsourcing experience for non-developers, the project is translated on [Transifex](https://www.transifex.com/qwertycube/apk-editor-studio/) with the following [instructions](https://github.com/kefir500/apk-editor-studio/wiki/Translation-Guide).
- When the translation is ready, I manually add the `.ts` files to the repo and update the referencing projects files, installer configurations, etc.

### Installer Translation

Creating multilingual installer is a good idea. However, personally I didn't go deep into the WiX Toolset localization methods due to the relative complexity of this installation tool. Hopefully, someday I'll get to it.

### Versioning

The project follows the semantic versioning, so I don't think the `1.1.50` beta would be a good idea. However, it's ok to push new feature/fix branches detached from the versioning.

**Comment by bovirus** [comment]
@kefir500 

Thanks for the reply.
Sorry for mismatch about versioning.
 I made some corrections at my my first post

**_Default branch_**

My proposal is to make 1.5.0  as default github branch (new project that you are dvelopping) and not master (=1.4.0 that seems a close project about a version already relased)

**_Translations_**

I propose you to add the important information that you posted before about translations in readme and in the frontend of github project.

**_New beta release_**

I propose you to compile and release a new program version (installer + portable) to enable all translators to check in place the new translations.

Is not possible to use version 1.4,.0 because the translation file name and language structure are different from 1.4.0 and 1.5.0.

Then to test the translations for 1.5.0 I believe that could be necessary a new installer/portanle program version.

**Comment by bovirus** [comment]
@kefir500 

Instructions how to use WIX to create multi-language MSI installer

https://stackoverflow.com/questions/2340605/is-it-possible-to-create-a-multilanguage-installer-using-wix

http://www.geektieguy.com/2010/03/13/create-a-multi-lingual-multi-language-msi-using-wix-and-custom-build-scripts/

**Comment by kefir500** [comment]
### Default Branch

> My proposal is to make 1.5.0 as default github branch (new project that you are developing) and not master (=1.4.0 that seems a close project about a version already released)

Currently the `1.5.0` branch reflects the intermediate project state. Due to its incompleteness I prefer to keep the `master` branch closer to the stable `1.4.0` for now. However, I'll consider your suggestion in the future release branches.

Also, I hope that people who are familiar with Git and GitHub are aware of the `git branch` command as well as the GitHub flow.

### Translations

> I propose you to add the important information that you posted before about translations in readme and in the frontend of github project.

Good idea. Thanks for the PR, I'll review it in a couple of days (right now I'm a little tied up at my fulltime job) and rephrase it a bit if you don't mind. 

### New beta release

> I propose you to compile and release a new program version (installer + portable) to enable all translators to check in place the new translations.

The snapshot build is automatically compiled on every commit. The related binaries can be found [here](https://github.com/kefir500/apk-editor-studio/releases/tag/development). Keep in mind that these releases might be unstable.

**Comment by bovirus** [comment]
Thanks for the info about beta.

I propose you add the info about latest beta build link

https://github.com/kefir500/apk-editor-studio/releases/tag/development

in the README.md file.

**Comment by kefir500** [comment]
I have merged your pull request, thanks.

Regarding the WiX translation. If I understand correctly, creating separate installers for each language is quite simple. However, when it comes to a multilingual installer, things get hard. According to the guide you linked above, external scripts and additional build steps are needed for this. Since APK Editor Studio is built at the continuous integration servers, resolving this dependencies will take time.

So (for now) I think I'll leave English as the only option.

**Comment by bovirus** [comment]
I agree with you. Thanks.
