### ISSUE TITLE
Version 1.5.0 (03.01.2021) - Strings untranslated

### ISSUE THREAD

**Issue by bovirus** [kefir500/apk-editor-studio#29]
@kefir500 

I just tested latest beta available here

https://github.com/kefir500/apk-editor-studio/releases/tag/development

Please change info in VERSION from 1.4.0 to 1.5.0.

The translation for Italian language is 100% translated but seems that there are some strings untraslated.

The follow strings are untranslated

File -> Open recent
File -> Open recent s Mo recent files
File ->  Install External APK...
File -> Optimzie External APK...
File -> Sign External APK...
Strumenti  -> View Signature
Finestra -> Open New Window

When I open an .APK file the File -> Open show as file type the string "Paccketto Android (*.apk)".
Where can I localize this string?

**Comment by bovirus** [comment]
Screenshots

![APK-Editor-Studio-1 5 0-GUI-01](https://user-images.githubusercontent.com/1262554/103488570-0aa49900-4e0e-11eb-8630-fe38dded7813.jpg)

![APK-Editor-Studio-1 5 0-GUI-02](https://user-images.githubusercontent.com/1262554/103488571-0bd5c600-4e0e-11eb-975a-74eaa5cbdb1d.jpg)

![APK-Editor-Studio-1 5 0-GUI-03](https://user-images.githubusercontent.com/1262554/103488573-0bd5c600-4e0e-11eb-8b61-5536977545b0.jpg)

![APK-Editor-Studio-1 5 0-GUI-04](https://user-images.githubusercontent.com/1262554/103488574-0c6e5c80-4e0e-11eb-8d67-e2c09e074534.jpg)

![APK-Editor-Studio-1 5 0-GUI-05](https://user-images.githubusercontent.com/1262554/103488575-0c6e5c80-4e0e-11eb-801f-b09a17131e9c.jpg)

![APK-Editor-Studio-1 5 0-GUI-06](https://user-images.githubusercontent.com/1262554/103488576-0d06f300-4e0e-11eb-816c-8b7c42502bfb.jpg)

![APK-Editor-Studio-1 5 0-GUI-07](https://user-images.githubusercontent.com/1262554/103488577-0d06f300-4e0e-11eb-90ed-55a11fd25f3b.jpg)

![APK-Editor-Studio-1 5 0-GUI-08](https://user-images.githubusercontent.com/1262554/103488578-0d9f8980-4e0e-11eb-80f4-3e32a2c6247a.jpg)

![APK-Editor-Studio-1 5 0-GUI-09](https://user-images.githubusercontent.com/1262554/103488579-0d9f8980-4e0e-11eb-9bf6-69b8e185a004.jpg)

![APK-Editor-Studio-1 5 0-GUI-10](https://user-images.githubusercontent.com/1262554/103488580-0e382000-4e0e-11eb-8a3d-c254464b5017.jpg)

**Comment by kefir500** [comment]
Thanks for testing.

As I mentioned in the issue #27, the snapshot build from the `1.5.0` branch is in an intermediate state.
- Some translations are not displayed due to the updated `tr` context which is currently in the transition process.
- The authors section is not translated because it is read from the global readme file.
- The `Paccketto Android (*.apk)` string is provided by the Qt Framework.
- Translatable strings reflecting the new features are still not present in the `.ts` files because most of them are under development and might change.

**Comment by bovirus** [comment]
@kefir500 

OK. Thanks.
Please stabilize/fix as much as possible the strings issues because it's important to understand if missing translation is bug or not.

**Comment by kefir500** [comment]
Done. Now the snapshot builds can be found [here](https://github.com/kefir500/apk-editor-studio/actions).

**Comment by bovirus** [comment]
@kefir500 

Thanks for teh update

There are some iisues

![image](https://user-images.githubusercontent.com/1262554/117531479-ef77af00-afe2-11eb-9601-369427fee23c.png)
Strings untranslated

![image](https://user-images.githubusercontent.com/1262554/117531494-fdc5cb00-afe2-11eb-9852-2531334c350b.png)
Menu option untranslated

![image](https://user-images.githubusercontent.com/1262554/117531508-0a4a2380-afe3-11eb-9b97-95f03d7b9b74.png)
Date in English format

![image](https://user-images.githubusercontent.com/1262554/117531520-17671280-afe3-11eb-9009-3cc6d74b6235.png)
If you can make an external file one for each language

![image](https://user-images.githubusercontent.com/1262554/117531539-2cdc3c80-afe3-11eb-9f81-4482bcd8f078.png)
Some values empty

Thanks. KR,

**Comment by kefir500** [comment]
### Strings untranslated

Seems that you are using the outdated build. The latest one is dated May 7.
- Since APK Editor Studio is migrating to the GitHub Actions, the snapshot builds can be found [here](https://github.com/kefir500/apk-editor-studio/actions).
- Open the first (the newest) workflow run (["Change artifacts naming"](https://github.com/kefir500/apk-editor-studio/actions/runs/821436107) at the moment of writing).
- Scroll to the bottom, there you will find the **Artifacts** section.

### Date format

This date is fetched from the standard predefined macros `__DATE__` and `__TIME__`. In fact, using these macros is a bad idea from the point of reproducible builds, so I'm planning to completely remove this line and use commit hashes instead (probably after replacing `qmake` with `CMake`).

### Authors section

Maintaining separate files for each language would be cumbersome since the Authors file contains the Markdown formatting with placeholders, links, etc. which makes it harder to prepare and translate via Transifex. The better way is to move the translatable strings to the source code itself, but this method also has several drawbacks and difficulties. I'll let you know if/when I implement this.

### Technologies section

These entries are empty because APK Editor Studio couldn't find Java on your system.

**Comment by bovirus** [comment]
@kefir500 

Thanks for the info.

Coudl you please enable multilanguage installer?
It's a very short job.

Thanks.

**Comment by kefir500** [comment]
> Could you please enable multilanguage installer?
> It's a very short job.

Or is it? I remember we were already discussing this question [here](https://github.com/kefir500/apk-editor-studio/issues/27#issuecomment-753760921).

I've been reading articles and forum posts regarding this functionality, and I got an impression that this process involves undocumented features such as embedding translations via external scripts, and requires building separate bundles for each language. This will have a serious impact on CI/CD.

Probably I'm missing something, but I haven't found any reliable and acceptable solution for now.
