### ISSUE TITLE
README.md - Add stable/beta download links

### ISSUE THREAD

**Issue by bovirus** [kefir500/apk-editor-studio#31]
@kefir500 

Please add in README the section Program download where you can add link for

stable build
https://github.com/kefir500/apk-editor-studio/tags

**_beta build_**
https://github.com/kefir500/apk-editor-studio/releases/tag/development

**_Note;: laetst beta build seems reported a wrong date (19.09.2018)._**

**Comment by kefir500** [comment]
Done.

Regarding the wrong date, this is explicitly stated in the release description. The technical reason for this discrepancy is that the compiled binary artifacts are automatically uploaded to the same old release. Creating a new tag/release for every commit is an option, however it is harder to maintain since the packages are built on different continuous integration services (Travis CI for Linux/macOS and AppVeyor for Windows). Probably moving to the GitHub Actions in the future will help.
