### ISSUE TITLE
Release Android Explorer as a separate standalone

### ISSUE THREAD

**Issue by hamedsbt** [kefir500/apk-editor-studio#37]
I'm using "Android Explorer" for my daily jobs and it works grate. So I have request to release "Android Explorer" as a separate standalone binary please.
Thank you...

**Comment by kefir500** [comment]
This is an interesting idea! I think I'll implement it in the upcoming APK Editor Studio v1.6.0.

**Comment by kefir500** [comment]
Hi again, @hamedsbt

Could you please elaborate, do you *literally* need a stand-alone *executable*? While implementing this feature, I realized that there are several modules shared between the APK Editor Studio and Android Explorer, such as:
- Translations
- Logging
- Settings
- Utilities

That's why I think that creating a completely independent executable is overkill. I decided to introduce the ability to run APK Editor Studio with a certain argument (`-e` or `--explorer`) that starts a stand-alone version of the Android Explorer. Also, the MSI installer creates a desktop shortcut for the Android Explorer, so there won't be much difference for the end-user. You can check out the latest development build [here](https://github.com/kefir500/apk-editor-studio/releases/download/development/apk-editor-studio_windows_1.6.0.msi).

However, maybe your situation requires a separate executable, that's why I'm asking for clarification on your specific use case.

**Comment by kefir500** [comment]
Closing the feature request as implemented.
Reopen if needed.
