### ISSUE TITLE
Smali code editing

### ISSUE THREAD

**Issue by marcussacana** [kefir500/apk-editor-studio#38]
Fisrt, Thanks for your program, I tested today modify a string in a hello world app in the smali decompiler and worked.
That Said, not sure if is just me who Don't know how to use the program properly yet or really is missing features.
Anyway I will say what I think will be cool to be included in the project:

First, The smali decompiler works but looks like he force us to open the decompiled folder and modify with an external text editor.
Personally I think will be very interesting to see the Apk Editor Studio creating a new tab only smali files to we directly open in the Apk Editor Studio with syntax highlighting and things like that.
Personally I think that's the most important thing.

Less important, but a cool feature will be a fast negation of conditional jumps and maybe display arrows in all jumps just like x64dbg or ollydbg does. 
![https://i.imgur.com/IlpK7aa.png](https://i.imgur.com/IlpK7aa.png)

**Comment by kefir500** [comment]
Hi,
Thanks a lot for your feedback!

I came to the conclusion that writing my own highlighting implementations on the top of the `QSyntaxHighlighter` is a pretty complex task. So I'm planning to move to the `KSyntaxHighlighting` module from the KDE Framework. It supports a pretty impressive [list](https://kate-editor.org/syntax/) of different formats, including `smali`. Since the 1.5.0 update has just landed, I hope to add this syntax highlighter (including the compelled `qmake` → `CMake` migration) in the APK Editor Studio v1.6.0.

Regarding the jump feature, I have no plans on implementing this in the nearest future. Probably, I will also perform the migration of the whole code editing module to the `KTextEditor` in future APK Editor Studio updates.

Regards,
Alexander

**Comment by marcussacana** [comment]
That's great! I'll wait the 1.6.0 release then :)

**Comment by amarroy6299** [comment]
I want to learn full smali course

**Comment by kefir500** [comment]
@amarroy6299 This is a pretty broad topic. Check out [this SO post](https://stackoverflow.com/questions/5656804/whats-the-best-way-to-learn-smali-and-how-when-to-use-dalvik-vm-opcodes).

**Comment by kefir500** [comment]
@marcussacana

- Migrated to `CMake` in c339cd6
- Migrated to `KSyntaxHighlighting` in 7740a93

It was a pretty massive task (primarily due to the `CMake` migration), but I'm happy to inform you that the code editor now supports the `smali` syntax highlighting. And again, adding [new formats](https://kate-editor.org/syntax/) should be a piece of cake from now. You can check out the latest dev build [here](https://github.com/kefir500/apk-editor-studio/releases/tag/development).

**Comment by marcussacana** [comment]
Good job 👍 Again, Thanks for the tool

**Comment by marcussacana** [comment]
Hell yeah, It looks like a professional tool now, even though it doesn't decompile for java, with its ability to remount it even reminds me of dnspy for .net :) good job man
