### ISSUE TITLE
Multilanguage EXE installer

### ISSUE THREAD

**Issue by bovirus** [kefir500/apk-editor-studio#44]
@kefir500 

I installed the latest official 1.5.0 version.

Thanks for this nrw stable version.

Is it possible to enable .exe instalelr with multilanguage instalelr?

The program is multilanguage but instalelr is mono language.

What kind of installer maker are you using?

Thanks.

**Comment by kefir500** [comment]
Hi @bovirus,

You have already asked similar questions [here](https://github.com/kefir500/apk-editor-studio/issues/27#issuecomment-753760921) and [here](https://github.com/kefir500/apk-editor-studio/issues/29#issuecomment-835783556).

The MSI installer is powered by WiX, you can see the source code [here](https://github.com/kefir500/apk-editor-studio/blob/1.6.0/scripts/windows/packages/msi/wix/main.wxs). I have no plans on creating and maintaining an EXE installer (e.g. built on NSIS) for several reasons:

- I find MSI more reliable since it's an official Windows installer format.
- Changing the installer type in midstream will have a negative effect on the user experience when it comes to software updates.
- Adding the new installer type will force us to maintain two separate packages, including the source code, continuous integration, and technical support.
- If you're talking about EXE bootstrapers produced by the WiX Burn, it's definitely an option. However, there are certain difficulties that I have already mentioned in my answers linked in the first paragraph.

Regards,
Alexander
