### ISSUE TITLE
При сборке апк бьет ошибку

### ISSUE THREAD

**Issue by weteroks** [kefir500/apk-editor-studio#63]
I: Using Apktool 2.6.0
I: Copying C:\Users\USER\AppData\Local\Temp\apk-editor-studio\apk\{5a78d378-cd8e-4621-ab56-cfa7e6cd2218} classes.dex file...
I: Building resources...
W: C:\Users\USER\AppData\Local\Temp\apk-editor-studio\apk\{5a78d378-cd8e-4621-ab56-cfa7e6cd2218}\res\values-v31\colors.xml:68: error: resource android:color/Indigo_800 is private.
W: C:\Users\USER\AppData\Local\Temp\apk-editor-studio\apk\{5a78d378-cd8e-4621-ab56-cfa7e6cd2218}\res\values-v31\colors.xml:69: error: resource android:color/Indigo_700 is private.
W: C:\Users\USER\AppData\Local\Temp\apk-editor-studio\apk\{5a78d378-cd8e-4621-ab56-cfa7e6cd2218}\res\values-v31\colors.xml:71: error: resource android:color/GM2_grey_800 is private.
W: C:\Users\USER\AppData\Local\Temp\apk-editor-studio\apk\{5a78d378-cd8e-4621-ab56-cfa7e6cd2218}\res\values-v31\colors.xml:72: error: resource android:color/Blue_800 is private.
W: C:\Users\USER\AppData\Local\Temp\apk-editor-studio\apk\{5a78d378-cd8e-4621-ab56-cfa7e6cd2218}\res\values-v31\colors.xml:73: error: resource android:color/Blue_700 is private.
W: error: failed linking references.
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\USER\AppData\Local\Temp\brut_util_Jar_61461278321448149256608643709329001819.tmp, link, -o, C:\Users\USER\AppData\Local\Temp\APKTOOL2246561254213341046.tmp, --package-id, 127, --min-sdk-version, 25, --target-sdk-version, 31, --version-code, 89, --version-name, 4.0.18, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, -e, C:\Users\USER\AppData\Local\Temp\APKTOOL1058837461426118934.tmp, -0, arsc, -I, C:\Users\USER\AppData\Local\apk-editor-studio\frameworks\1.apk, --manifest, C:\Users\USER\AppData\Local\Temp\apk-editor-studio\apk\{5a78d378-cd8e-4621-ab56-cfa7e6cd2218}\AndroidManifest.xml, C:\Users\USER\AppData\Local\Temp\apk-editor-studio\apk\{5a78d378-cd8e-4621-ab56-cfa7e6cd2218}\build\resources.zip]

**Comment by weteroks** [comment]
причем даже не внося никаких изминений всеравно не собирает

**Comment by S1ROZHA** [comment]
Same me problem

**Comment by Ibuprophen** [comment]
It appears (to me) that this issue is tied specifically to Apktool as the issue is likely the Apps Obfuscation. 

This software helps in utilizing the tools provided by the Apktool.jar and this issue may better fit being reported to the Apktool Github repository (from the developer iBotPeaches). 

Just my personal opinion based upon my findings... 

Good Luck! 

~Ibuprophen

**Comment by kefir500** [comment]
Hi everyone,

Sorry for my long absence.
I don't have much spare time for APK Editor Studio due to my full-time job.

Most likely, the issue is the outdated Apktool.
For now, you can manually download the latest [Apktool release](https://github.com/iBotPeaches/Apktool/releases) and select it in the APK Editor Studio settings.
However, the upcoming APK Editor Studio will include the automatic Apktool updater which will keep it up to date.

**Comment by kefir500** [comment]
[APK Editor Studio v1.7.0](https://github.com/kefir500/apk-editor-studio/releases/tag/v1.7.0) containing the most recent Apktool is out.
