### ISSUE TITLE
Exit Code 1

### ISSUE THREAD

**Issue by Developer-Mike** [kefir500/apk-editor-studio#67]
I: Using Apktool 2.6.0
I: Smaling smali folder into classes.dex...
I: Smaling smali_classes2 folder into classes2.dex...
I: Smaling smali_classes3 folder into classes3.dex...
I: Building resources...
W: C:\Users\delta\AppData\Local\Temp\apk-editor-studio\apk\{d233a777-84c4-4628-bbdb-430101ea1245}\res\values-v31\colors.xml:55: error: resource android:color/Indigo_800 is private.
W: C:\Users\delta\AppData\Local\Temp\apk-editor-studio\apk\{d233a777-84c4-4628-bbdb-430101ea1245}\res\values-v31\colors.xml:56: error: resource android:color/Indigo_700 is private.
W: C:\Users\delta\AppData\Local\Temp\apk-editor-studio\apk\{d233a777-84c4-4628-bbdb-430101ea1245}\res\values-v31\colors.xml:58: error: resource android:color/GM2_grey_800 is private.
W: C:\Users\delta\AppData\Local\Temp\apk-editor-studio\apk\{d233a777-84c4-4628-bbdb-430101ea1245}\res\values-v31\colors.xml:59: error: resource android:color/Blue_800 is private.
W: C:\Users\delta\AppData\Local\Temp\apk-editor-studio\apk\{d233a777-84c4-4628-bbdb-430101ea1245}\res\values-v31\colors.xml:60: error: resource android:color/Blue_700 is private.
W: error: failed linking references.
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\delta\AppData\Local\Temp\brut_util_Jar_16508697905250004684188828881420378147.tmp, link, -o, C:\Users\delta\AppData\Local\Temp\APKTOOL4530337816857735466.tmp, --package-id, 127, --min-sdk-version, 24, --target-sdk-version, 31, --version-code, 2000000349, --version-name, 3.4.9, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, -e, C:\Users\delta\AppData\Local\Temp\APKTOOL8070492580726245008.tmp, -0, arsc, -I, C:\Users\delta\AppData\Local\apk-editor-studio\frameworks\1.apk, --manifest, C:\Users\delta\AppData\Local\Temp\apk-editor-studio\apk\{d233a777-84c4-4628-bbdb-430101ea1245}\AndroidManifest.xml, C:\Users\delta\AppData\Local\Temp\apk-editor-studio\apk\{d233a777-84c4-4628-bbdb-430101ea1245}\build\resources.zip]

**Comment by Ibuprophen** [comment]
This is typically a Windows OS specific code as Exit status 1 can mean literally anything that the Windows system is unable to identify the specific issue/error. 

These status codes are sometimes defined by the program itself, and in most cases you'll find 1 used as a catch-all for every possible failure.

(Many GUI apps don't propagate errors to the exit status at all, since practically nothing checks it.)

The command-line tools sometimes use different codes that allows for easier scripting, and those typically reserve 1 as the "something unknown happened" catch-all.

I believe that this is an issue regarding something that the Apktool is unable to perform for various reasons. 

I believe that this is something that should actually be an issue opened up in the Apktool Github Repository for iBotPeaches. 

Good Luck! 

~Ibuprophen

**Comment by Developer-Mike** [comment]
I have decompiled and built it successfully with apktool.

**Comment by kefir500** [comment]
Hi @Developer-Mike,

Sorry for the delay.

Seems that the issue is the outdated Apktool.
You can manually download the latest Apktool release and select it in the APK Editor Studio settings.

Nevertheless, the upcoming APK Editor Studio will include the automatic Apktool updater which will keep it up to date.

Regards,
Alexander
