### ISSUE TITLE
APK error when changing SDK to version 31

### ISSUE THREAD

**Issue by henriquelucas** [kefir500/apk-editor-studio#72]
I can change the SDK version to 31 of an apk and recompile without problems. But when I install the apk on the android device it returns me: There was a problem parsing package

**Comment by kefir500** [comment]
- Have you tried the latest APK Editor Studio v1.7.0?
- Are you changing the SDK version by manually editing the XML manifest, or via the top-right dock panel?

Also, there is a high possibility that the specified SDK doesn't support some features present in the original SDK version. That's why the recompilation goes fine with no errors until you try installing the APK.

**Comment by Ibuprophen** [comment]
Just a thought... 

Since Parsing is a type of method the Android performs in analyzing certain data strings, this is typically common when unsuccessfully/incorrectly attempting to change the name of an the app/apk and/or the package name. 

In that case, this attempt requires additional work throughout the app/apk itself and can range from some simple tasks to a more advanced/difficult task(s). 

I hope I had explained this okay via text... 
 
~Ibuprophen

**Comment by kefir500** [comment]
Closing the issue.
See my previous message regarding the SDK incompatibility.
Feel free to reopen if needed.
