### ISSUE TITLE
Where is the Arabic language ?

### ISSUE THREAD

**Issue by SWxEng** [kefir500/apk-editor-studio#74]
Hi @kefir500 
.
Where is the Arabic language ?
in APK Editor Studio v1.6.0
.
![image](https://user-images.githubusercontent.com/55116927/192897700-26c992a9-1185-415e-bc43-3acf9a12d258.png)

**Comment by kefir500** [comment]
Hi @SWxEng,

Sorry for the delay.
I don't have much spare time for APK Editor Studio due to my full-time job.

The Arabic translation will be included in the upcoming release.

Thank you for waiting.

**Comment by SWxEng** [comment]
No Problem
.
OK
Thank you

**Comment by kefir500** [comment]
Hi again,

Some unfortunate news here.

Looking at the Transifex dashboard, I had an impression that the Arabic translation was finished. However, I just checked the content and found out that one of the contributors simply copied the original English values without actually translating them. Furthermore, he overwrote the proper strings translated by other contributors.

I haven't found a way to remove someone's contribution in the Transifex interface, so I had to manually restore everything to the normal state. Now I think of moving to another localization management service, but that's a completely different story.

Anyway, it turns out that the Arabic translation is only 30% complete, which means it's not ready for the release. So, unfortunately, there will be no Arabic translation until someone actually brings it to a more or less complete state.

Kindest regards,
Alexander

**Comment by SWxEng** [comment]
Ok, I will translate
.
https://explore.transifex.com/qwertycube/apk-editor-studio/

**Comment by SWxEng** [comment]
@kefir500 

Now Arabic 100% in transifex

**Comment by kefir500** [comment]
@SWxEng,

**Adgk** is your account on Transifex, isn't it?
If yes, then thanks a lot for your contribution!

Just one thing: you have translated the "%" arguments as "٪" (Arabic percent sign), however the [guide](https://github.com/kefir500/apk-editor-studio/wiki/Translation-Guide) I sent you on Transifex explicitly states the importance of keeping it as-is. I've already fixed these strings, however, please be careful in the future.

I'm planning to release the v1.7.1 update in the nearest future containing some hotfixes.
This version will also include the Arabic translation.

Just one question: how should I mention you in the authors list?

**Comment by SWxEng** [comment]
@kefir500 hi
yes me Adgk ....  account on Transifex
.
ok , Thank you
.
Author Translator
Arabic Egypt
SWxEng - https://github.com/SWxEng
